CREATE TABLE IF NOT EXISTS registry (
    id INT(5) NOT NULL AUTO_INCREMENT,
    name VARCHAR(80) NOT NULL,
    last_name VARCHAR(80) NOT NULL,
    phone VARCHAR(15) DEFAULT NULL,
    street VARCHAR(100) DEFAULT NULL,
    city VARCHAR(100) DEFAULT NULL,
    postal_code VARCHAR(12) DEFAULT NULL,
    country VARCHAR(100) DEFAULT NULL,
    email VARCHAR(120) UNIQUE NOT NULL,
    web_page VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY(id)
    );


